### ISSUE TITLE
Setup Theme

### ISSUE THREAD

**Issue by me-imfhd** [Praashh/anchor-playground#2]
- [ ] Remove Default Code
- [ ] Setup Tailwind
- [ ] Setup Shacn
- [ ] Initialize Reusable Components
- [ ] Build UI Components

**Comment by Praashh** [comment]
![image](https://github.com/user-attachments/assets/0b79a81c-a3b9-4cd3-a8d6-bba21037e8d7)
 
 
 Setup Theme completed.
